### ISSUE TITLE
panels: prototype teleport/elevator transitions

### ISSUE THREAD

**Issue by jackmakesthings** [jackmakesthings/game-dev#123]
May need to revise scene-loading before tackling this one, but goal is to prototype a transition between two spaces that aren't adjacent (so no pan-over effect, probably).

**Comment by jackmakesthings** [comment]
@Batbro I'm thinking of "teleporters" but that could also mean "elevator" or anything else along those lines - something that changes scenes without visually "moving" the player. We'll need this, right?

**Comment by Batbro** [comment]
It feels like we're inevitably going to have areas where the camera-pan transition will not be an option, because the angle from which you're viewing the two rooms changes.  A quick fade-to-black is the obvious solution, but I'd prefer to come up with something that still visually follows Trace and conveys a sense of direction.  Requires some thought, and might require handling on a case-by-case basis.

Your mention of elevators does give me a neat idea for something though...

**Comment by jackmakesthings** [comment]
Updating this to include elevators, which we're more likely to need in the immediate future than teleporters.
